# 日志配置
logging:
    # 设置日志文件存放目录为当前登录用户的主目录
    file:  ${user.home}/logs/spring-boot-mybatis.log
    # 下面设置单个日志文件最大为10MB,只保存30天内日志，超过时间自动删除
    file.max-size: 10MB
    file.max-history: 30
    level:
        # root 级别即项目的所有日志默认输出为info
        root: info
        # 本项目开发使用debug,测试上线后使用info
        com.bearcat2: debug
        # spring 日志输出设置为warn,避免大量日志输出
        org.springframework: warn

# 配置 druid 数据源,参考配置 https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE
spring:
    datasource:
        druid:
            # 配置连接的基本属性,注意mysql驱动6以上版本url中需指定serverTimezone时区
            username: root
            password: 123456
            url: jdbc:mysql://localhost:3306/spring-boot-mybatis?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
            driver-class-name: com.mysql.cj.jdbc.Driver
            # 配置初始化大小、最小、最大连接数
            initial-size: 5
            min-idle: 5
            max-active: 20
            # 配置获取连接等待超时的时间,单位毫秒
            max-wait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置连接校验
            validationQuery: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            # 打开PSCache，指定每个连接上PSCache的大小
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            # 配置监控统计拦截的filters
            filters: stat,wall
            async-init: true
    # thymeleaf 配置
    thymeleaf:
        # 控制不缓存页面,避免刷新不显示最新内容,线上时记得开启,提升页面响应速度
        cache: false

# mybatis 配置
mybatis:
    # mybatis主配置文件所在路径
    config-location: classpath:mybatis/mybatis.cfg.xml
    # 给下面包及所有子包下的类取别名(默认为类名)
    #    type-aliases-package: com.bearcat2.entity
    # 指定mapper映射文件的位置
    mapper-locations:
        - classpath:mybatis/mapper/**/*.xml

# pagehelper分页插件
pagehelper:
    #设置数据库方言
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 配置项目名,默认 /
#server:
#    servlet:
#        context-path: /bearcat2
