# 日志配置
logging:
    # 设置日志文件存放目录为当前登录用户的主目录
    file:  ${user.home}/logs/spring-boot-mybatis.log
    # 下面设置单个日志文件最大为10MB,只保存30天内日志，超过时间自动删除
    file.max-size: 10MB
    file.max-history: 30
    level:
        # root 级别即项目的所有日志默认输出为info
        root: info
        # 本项目开发使用debug,测试上线后使用info
        com.bearcat2: debug

# 配置 druid 数据源,参考配置 https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE
spring:
    datasource:
        druid:
            # 配置连接的基本属性,注意mysql驱动6以上版本url中需指定serverTimezone时区
            username: root
            password: 123456
            url: jdbc:mysql://localhost:3306/spring-boot-mybatis?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
            driver-class-name: com.mysql.cj.jdbc.Driver
            # 配置初始化大小、最小、最大连接数
            initial-size: 5
            min-idle: 5
            max-active: 20
            # 配置获取连接等待超时的时间,单位毫秒
            max-wait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置连接校验
            validationQuery: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            # 打开PSCache，指定每个连接上PSCache的大小
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            # 配置监控统计拦截的filters
            filters: stat,wall
            async-init: true
    # 在项目启动时执行下面脚本
    #        schema: classpath:sql/table.sql
    #        data: classpath:sql/data.sql
    #        initialization-mode: always

    # thymeleaf 配置
    thymeleaf:
        # 控制不缓存页面,避免刷新不显示最新内容,线上时记得开启,提升页面响应速度
        cache: false

    # redis 配置
    redis:
        host: 127.0.01
        port: 6379
        password: asdf
        # 连接超时时间,单位毫秒
        timeout: 10000
        database: 0
        lettuce:
            pool:
                # 连接池最大连接数(使用负值表示没有限制)
                max-active: 10
                # 连接池最大空闲连接数
                max-idle: 8
                # 连接池最小空闲连接数
                min-idle: 2
                # 连接池最大阻塞时间,单位毫秒(使用负值表示没有限制)
                max-wait: -1

# mybatis 配置
mybatis:
    type-aliases-package: com.bearcat2.entity
    # 指定xml映射文件位置
    mapper-locations:
        - classpath:mapper/**/*.xml

# 通用mapper配置
mapper:
    mappers:
        - com.bearcat2.mapper.CommonMapper
    # 该配置指定在插入数据时忽略空串
    not-empty: true

# pagehelper分页插件配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# session 超时时间设置为1小时,单位是秒
server:
    servlet:
        session:
            timeout: 3600

# 自定义属性
bearcat2:
    # 定义系统名
    systemName: 通用前端管理系统
    # 配置超级用户用户名和密码
    superUser:
        username: admin
        password: 123456